# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='imagem/')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemClassificada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeBase64', models.TextField()),
            ],
        ),
    ]
